name: Release Action
run-name: ${{ github.actor }} is releasing out Action
on: [push]
jobs:
  Semantic-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branch: release
          # tag_format: ${version}
          # extra_plugins: |
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
